### ISSUE TITLE
1.4 is missing Conn.Request()

### ISSUE THREAD

**Issue by holygeek** [googollee/go-socket.io#161]
In my code that uses the old go-socket.io version I used `socketio.Socket.Request()` to get the original `*http.Request` that initiates the socket connection. I used this for getting the cookies associated with the connection.

Now with 1.4 `socketio.Conn` I can no longer do that, there is no `Conn.Request()`, but there is `Conn.RemoteHeader()` so a work around is to manually process the returned `http.Header` in order to look for the cookie.

It would be easier if `socketio.Conn` had a `Request()` method to simplify this.

Does it makes sense to add `socket.Coon.Request()` method or is it no longer appropriate?

**Comment by googollee** [comment]
Thank you for testing the latest code. I'm really glad to hear the feedback.

Currently, you can grab *http.Request through setting a function in Config.RequestChecker. But seems it separated from Conn now.

Yes. I can add Conn.Request(). And it will return the first http.Request(Connect request) of this connection. Which means if you use polling transport, it will only return the first http.Request, regardless whatever it changes during the following request.

Is it OK?

**Comment by holygeek** [comment]
As long as the connection ID() remains the same, and is associated with the first request, then I guess it is okay. In other words, the same go-socket.io.Conn.ID() is made by multiple, different http requests in the case of long polling, right?

**Comment by googollee** [comment]
It depends:

 - If the transport is websocket, there is only one HTTP connection and only one request of course. The following reading/writing will reuse on this connection.
 - If the transport is polling, all request is the short connection. It will use POST/GET to simulate one connection and every POST/GET will contain its request. But I think the first one is more important because it should contain all information for the session.

Besides, keeping the first request is much simple, which is received before session creating. It's better for both implement and performance.

**Comment by googollee** [comment]
And as http.Request contains a lot of reference field, the user must not change its contents to avoid race condition.

**Comment by holygeek** [comment]
That sounds good!

**Comment by googollee** [comment]
Just make a quick fix. Please update both go-socket.io and go-engine.io. You can custom engineio.Options.ConnInitor to init a Conn with *http.Request and Conn.SetContext.

**Comment by holygeek** [comment]
I'm halfway updating my code to use the 1.4 go-socket.io. I noticed that the `OnConnect` event is not dispatched - [this line](https://github.com/googollee/go-socket.io/blob/v1.4/example/main.go#L18) is never printed to the console when running the example program. Is that a bug?

**Comment by mihok** [comment]
I'm also interested in getting the http.Request() from the Conn to pull an extra GET parameter with the initial socket connection.

**Comment by justinkiang** [comment]
Sorry to bring this back up 4 years later, but I see that @googollee you mentioned to do a Conn.SetContext in the Conninitor of the server.

How would I access that within an event handler?  Since the ConnInitor is setting the context in an engineio.Conn, and I only get a socketio.Conn in the handler

I have this in the server initilization
`ConnInitor: func(r *http.Request, s engineio.Conn) {
			s.SetContext(r.Context())
		},`
