### ISSUE TITLE
[BUG] On event handler has go routine, connection connection will close

### ISSUE THREAD

**Issue by ibuler** [googollee/go-socket.io#240]
**Describe the bug**
In the chat example,  I rewrite the OnEvent notice handler using go routine, then connection will be disconnect, and client will be reconnect

```
        server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
		go func() {
			for i:=0;i<100;i++ {
				s.Emit("reply", "have "+msg)
				time.Sleep(1 * time.Second)
			}
		}()
	})
```

See log:
meet error: websocket: write closed
meet error: websocket: write closed
meet error: websocket: write closed

**Expected behavior**
I want when emit notice event, then send msg to client per second,

**Environment (please complete the following information):**
 - Go version: v1.12.5
 - Server version v1.4
 - Client version socket.io v1.4

**Other**
May be see when I implement a web tail file server, When user tail a file, server will send the file data to client until close, so How to do it

**Comment by lemontreehuang** [comment]
The same error! Have you fixed it?

**Comment by zhouruisong** [comment]
do you fix it?

**Comment by mrfoe7** [comment]
@ibuler Hi.
Your code is not correctly. You don't synchronized goroutine. If i understood correctly, you wanna send message to client with 1 second delay. It is my way to resolve your problem. If you wanna send message to client every second try to use time.NewTicker

Example with Time.Sleep:
```go
server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
	wg := &sync.WaitGroup{}
	wg.Add(1)
	go func(*sync.WaitGroup) {
		time.Sleep(1 * time.Second)
		s.Emit("reply", "have "+msg)
		wg.Done()
	}(wg)
	wg.Wait()
})
```

I may suggest error message - "meet error: websocket: write closed" not related with your expected behavior.
