### ISSUE TITLE
Remove panic from source code

### ISSUE THREAD

**Issue by sshaplygin** [googollee/go-socket.io#293]

**Comment by googollee** [comment]
I don't think removing panic is reasonable. It's useful when parsing/unparsing.

**Comment by mrfoe7** [comment]
I know to it. Panic use only in handler.go file. At now use `f interface{}` at parameter at `newEventFunc` and `newAckFunc` i think it is not best way. Because user caught panic at runtime  We can use new type [HandlerFunc](https://github.com/gin-gonic/gin/blob/d5f12ac6d7ba14b9bc85fa7d0ae486289d52bdf1/gin.go#L28) as gin-gonic way, because we used four signature at **OnEvent** in practice `func(s socketio.Conn, msg string)`, `func(s socketio.Conn, msg string) string`,  `func(s socketio.Conn) string`. I suggest all callback use as `func (c socketio.Context)`. Remaining handlers similar callback at **OnEvent** handlers

But we need refactor all source code to integrate my suggest. It theme linked with this [issue](https://github.com/googollee/go-socket.io/issues/275)

Panic code:
* [code1](https://github.com/googollee/go-socket.io/blob/master/handler.go#L20)
* [code2](https://github.com/googollee/go-socket.io/blob/master/handler.go#L16)
* [code3](https://github.com/googollee/go-socket.io/blob/master/handler.go#L38)

**Comment by googollee** [comment]
That's fine. So the feature is to make a register function with a context instead of interface{}, but not remove panic.

I think to making another issue and giving some background would be better.

**Comment by googollee** [comment]
Or, shall we dup this to  #275?
