### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by fd** [googollee/go-socket.io#57]
Currently there is only the Server API. Are there any plans to add a client as well?

**Comment by acoyfellow** [comment]
You use the normal JS client side library from Socket.io

**Comment by fd** [comment]
No, I meant a Go client.

**Comment by googollee** [comment]
Well, I want to write a client, but seems I don't have enough time to do it. :(

**Comment by rykov** [comment]
+1

**Comment by abo** [comment]
+1

**Comment by AnatoliiPrylutskyi** [comment]
It will be great +1

**Comment by alu0075** [comment]
+1

**Comment by bailongxian** [comment]
+1

**Comment by rykov** [comment]
As a popular feature request, can we get a few more backers and get this done?

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=7524138)](https://www.bountysource.com/issues/7524138-client-api?utm_source=7524138&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by elimisteve** [comment]
+1

**Comment by pkxiuluo** [comment]
+1

**Comment by elimisteve** [comment]
Just added a $15 bounty for this; thank you @rykov for the idea.

Would love to see this feature!

**Comment by erkie** [comment]
For now it seems that it makes more sense to create a separate repo/project for a go client of the Socket.io standard. It's awesome to see so much interest, but right now there's not enough momentum in the form of maintainers or contributors to make this happen within a reasonable timeframe. That's why I'm closing this (not sure what happens with the bounty posted above...) 

If anyone disagrees feel free to comment and I'lll reopen it :)
